---
title: "Ellie antibody binding"
author: "Dillon Corvino"
date: "26/10/2023"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: united
    highlight: tango
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

Built with R version `r getRversion()`

## Setup {.tabset}

### Dataset information
```{r Dataset_Info}



```

### Environment
```{r setup}

knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,  
  eval = TRUE, 
  tidy = TRUE
)

knitr::opts_knit$set(
  root.dir = "../"
)


# Environment Set up
rm(list = ls()) #Clean workspace
cat("\014")     #Clean Console
gc() # Free memory

# Establish working directory
library("rstudioapi")

# Set working directory to source file location
setwd(dirname(getActiveDocumentContext()$path))
setwd("..")



output.dir <- "results/"
if(!dir.exists(output.dir)){
  dir.create(output.dir, 
             recursive = T)}

```

### read data
```{r read_data}

# file path 
#file.path <- c("alksdja;dj")


data.files <- list.files("data/Exp_1/", full.names = T)


# remove path and derive unique file names
file.names <- gsub("data/Exp_1//2023-10-25_ET23-37_00._", "", data.files)
file.names <- gsub(" ", "_", file.names)
file.names <- gsub("\\.", "_", file.names)
file.names <- gsub("_csv", "", file.names)

file.names

input.data <- list()

for(i in seq_along(data.files)){
  
data.temp <- read.csv(data.files[i], header = T, row.names = NULL)

# note, colnames are shifted one over so just rename the colnames 
colnames(data.temp) <- c("Time_seconds", "Binding_nm", "Step_info")

data.temp$Time_seconds <- as.numeric(data.temp$Time_seconds)

# remove step info for now
data.temp <- data.temp[,-3]

input.data[[i]] <- data.temp
names(input.data)[i] <- file.names[i]

}

# get step positions 
data.temp <- read.csv(data.files[1], header = T, row.names = NULL)

# note, colnames are shifted one over so just rename the colnames 
colnames(data.temp) <- c("Time_seconds", "Binding_nm", "Step_info")
step.info <- data.temp %>%
  dplyr::filter(Step_info != "") %>%
  dplyr::select(Time_seconds, Step_info)
step.info$Time_seconds <- as.numeric(step.info$Time_seconds)





library(ggplot2)
library(reshape2)


combined_data <- do.call(rbind, lapply(names(input.data), function(x) cbind(input.data[[x]], L1 = x)))

# Create a line plot with modified aesthetics
ggplot(combined_data, aes(x = Time_seconds, y = Binding_nm, color = L1)) +
  geom_line() +
  labs(x = "Time (seconds)", y = "Binding (nm)", title = "Binding Over Time") +
  scale_x_continuous(breaks = seq(0, max(combined_data$Time_seconds) + 50, by = 20), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, max(combined_data$Binding_nm) + 1, by = 0.5), expand = c(0, 0)) +
  theme_minimal() +
  theme(axis.line = element_line(color = "black"),
        panel.grid.major = element_line(colour = "grey"),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        #legend.title = element_text(text = "Legend Title"),
        legend.position = "top") +
  theme(legend.direction = "horizontal",
        legend.key.width = unit(2, "cm"),
        legend.key.height = unit(0.5, "cm"),
        plot.title = element_text(hjust = 0.5)) +
  coord_fixed(ratio = 30) +  # Adjust width and height ratio
    geom_vline(data = step.info, aes(xintercept = Time_seconds, color = Step_info), linetype = "dashed") +
  geom_text(data = step.info, aes(x = Time_seconds, y = 0, label = paste0("Step_", Step_info)), vjust = -1.5) 


ggplot(combined_data, aes(x = Time_seconds, y = Binding_nm, color = L1)) +
  geom_line() +
  labs(x = "Time (seconds)", y = "Binding (nm)", title = "Binding Over Time") +
  scale_x_continuous(breaks = seq(0, max(combined_data$Time_seconds) + 50, by = 20), expand = c(0, 0)) +
  scale_y_continuous(breaks = seq(0, max(combined_data$Binding_nm) + 2, by = 0.5), limits = c(0, max(combined_data$Binding_nm) + 1), expand = c(0, 0)) +
  theme_minimal() +
  theme(axis.line = element_line(color = "black"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor = element_line(color = "grey", linetype = "solid"),
        panel.grid.minor.x = element_blank(),
        panel.border = element_blank(),
        #legend.title = element_text(text = "Legend Title"),
        legend.position = "top", 
        axis.text = element_text(color = "black"),
        axis.title = element_text(color = "black")) +
  theme(legend.direction = "horizontal",
        legend.key.width = unit(2, "cm"),
        legend.key.height = unit(0.5, "cm"),
        plot.title = element_text(hjust = 0.5, size = 30)) +
  coord_fixed(ratio = 30) +  # Adjust width and height ratio
  geom_vline(data = step.info, aes(xintercept = Time_seconds, color = Step_info), linetype = "dashed", color = "black", show.legend = FALSE) #+
  geom_text(aes(x = 5, y = 6, label = "temp"), vjust = -1)


ggsave("temp.pdf")
  
  
  geom_vline(xintercept = 0.5, linetype = "dashed", color = "red") +  # Add vertical line at x = 0.5
  geom_text(aes(x = 0.5, y = max(Binding_nm) + 0.005, 
                label = "Special point"), 
            vjust = -1)  # Add text above the line



 # coord_cartesian(xlim = c(0, max(combined_data$Time_seconds) + 0.2), ylim = c(0, max(combined_data$Binding_nm) + 0.01)) +




```




